
const productos = [
    {
        id: "prod-001",
        nombre: "Milanesa de Cerdo",
        precio: 10000,
        imagen: "../Imagenes/Milanesa.png",
        categoria: "Carnes"
    },

    {
        id: "prod-002",
        nombre: "Chuleta de Cerdo",
        precio: 8500,
        imagen: "../Imagenes/Chuleta.png",
        categoria: "Carnes"
    },

    {
        id: "prod-003",
        nombre: "Hueso de res",
        precio: 4500,
        imagen: "../Imagenes/Lomo.png",
        categoria: "Carnes"
    },

    {
        id: "prod-004",
        nombre: "Sobrebarriga delgada",
        precio: 14000,
        imagen: "../Imagenes/Sobrebarriga.png",
        categoria: "Carnes"
    },

    {
        id: "prod-005",
        nombre: "Platano Verde 1 und",
        precio: 1000,
        imagen: "../Imagenes/Platano.png",
        categoria: "Verduras"
    },

    {
        id: "prod-006",
        nombre: "Piña 1 und",
        precio: 5500,
        imagen: "../Imagenes/Piña.png",
        categoria: "Verduras"
    },

    {
        id: "prod-007",
        nombre: "Granadilla 1 und",
        precio: 1900,
        imagen: "../Imagenes/Granadilla.png",
        categoria: "Verduras"
    },

    {
        id: "prod-008",
        nombre: "Coco 1 und",
        precio: 10000,
        imagen: "../Imagenes/Coco.png",
        categoria: "Verduras"
    },
    
    {
        id: "prod-009",
        nombre: "Detodito BBQ",
        precio: 19000,
        imagen: "../Imagenes/Detodito.png",
        categoria: "Lonchera"
    },

    {
        id: "prod-010",
        nombre: "Detodito Mix",
        precio: 8600,
        imagen: "../Imagenes/Detoditos.png",
        categoria: "Lonchera"
    },

    {
        id: "prod-011",
        nombre: "Choclitos Limón",
        precio: 7500,
        imagen: "../Imagenes/Choclitos.png",
        categoria: "Lonchera"
    },

    {
        id: "prod-012",
        nombre: "Doritos Mega Queso",
        precio: 13500,
        imagen: "../Imagenes/Doritos.png",
        categoria: "Lonchera"
    },

    {
        id: "prod-013",
        nombre: "Servilletas 200 und",
        precio: 2100,
        imagen: "../Imagenes/Servilletas.png",
        categoria: "Aseo"
    },

    {
        id: "prod-014",
        nombre: "Lavaloza Crema Limón",
        precio: 2400,
        imagen: "../Imagenes/Lavaloza.png",
        categoria: "Aseo"
    },
    
    {
        id: "prod-015",
        nombre: "Toalla Cocina 44 und",
        precio: 3900,
        imagen: "../Imagenes/Toalla.png",
        categoria: "Aseo"
    },
    
    {
        id: "prod-016",
        nombre: "Quitamanchas 850 gr",
        precio: 53600,
        imagen: "../Imagenes/Quitamanchas.png",
        categoria: "Aseo"
    }
];